@startuml UC_05_DichVu
left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam shadowing false
skinparam usecase {
  BackgroundColor white
  BorderColor #222222
  ArrowColor #222222
  FontSize 13
}
skinparam rectangle {
  BorderColor #222222
  BackgroundColor white
}

actor "Super admin" as SuperAdmin

rectangle "Hệ thống StayHub Admin Web" {
  usecase "Quản lí dịch vụ" as Main
  usecase "Xem danh sách dịch vụ" as ListServices
  usecase "Xem chi tiết dịch vụ" as ViewService
  usecase "Thêm dịch vụ" as AddService
  usecase "Sửa dịch vụ" as EditService
  usecase "Xóa dịch vụ" as DeleteService
  usecase "Chuyển trạng thái dịch vụ" as ServiceStatus
}

ListServices ..> Main : <<extend>>
ViewService ..> Main : <<extend>>
AddService ..> Main : <<extend>>
EditService ..> Main : <<extend>>
DeleteService ..> Main : <<extend>>
ServiceStatus ..> Main : <<extend>>
SuperAdmin -- Main
@enduml
