@startuml UC_08_KhachThue
left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam shadowing false
skinparam usecase {
  BackgroundColor white
  BorderColor #222222
  ArrowColor #222222
  FontSize 13
}
skinparam rectangle {
  BorderColor #222222
  BackgroundColor white
}

actor "Super admin" as SuperAdmin
actor "Quản lý tòa nhà" as BuildingManager

rectangle "Hệ thống StayHub Admin Web" {
  usecase "Quản lí khách thuê" as Main
  usecase "Xem danh sách khách thuê" as ListTenants
  usecase "Xem chi tiết khách thuê" as ViewTenant
  usecase "Thêm khách thuê" as AddTenant
  usecase "Sửa khách thuê" as EditTenant
  usecase "Xóa khách thuê" as DeleteTenant
  usecase "Chuyển trạng thái khách thuê" as TenantStatus
  usecase "Tìm kiếm/lọc khách thuê" as FilterTenant
}

ListTenants ..> Main : <<extend>>
ViewTenant ..> Main : <<extend>>
AddTenant ..> Main : <<extend>>
EditTenant ..> Main : <<extend>>
DeleteTenant ..> Main : <<extend>>
TenantStatus ..> Main : <<extend>>
FilterTenant ..> Main : <<extend>>
SuperAdmin -- Main
BuildingManager -- Main
@enduml
