@startuml UC_09_PhuongTien
left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam shadowing false
skinparam usecase {
  BackgroundColor white
  BorderColor #222222
  ArrowColor #222222
  FontSize 13
}
skinparam rectangle {
  BorderColor #222222
  BackgroundColor white
}

actor "Super admin" as SuperAdmin
actor "Quản lý tòa nhà" as BuildingManager

rectangle "Hệ thống StayHub Admin Web" {
  usecase "Quản lí phương tiện" as Main
  usecase "Xem danh sách phương tiện" as ListVehicles
  usecase "Xem chi tiết phương tiện" as ViewVehicle
  usecase "Thêm phương tiện" as AddVehicle
  usecase "Sửa phương tiện" as EditVehicle
  usecase "Xóa phương tiện" as DeleteVehicle
  usecase "Chuyển trạng thái phương tiện" as VehicleStatus
  usecase "Tìm kiếm/lọc phương tiện" as FilterVehicle
}

ListVehicles ..> Main : <<extend>>
ViewVehicle ..> Main : <<extend>>
AddVehicle ..> Main : <<extend>>
EditVehicle ..> Main : <<extend>>
DeleteVehicle ..> Main : <<extend>>
VehicleStatus ..> Main : <<extend>>
FilterVehicle ..> Main : <<extend>>
SuperAdmin -- Main
BuildingManager -- Main
@enduml
