@startuml UC_17_BaoTri
left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam shadowing false
skinparam usecase {
  BackgroundColor white
  BorderColor #222222
  ArrowColor #222222
  FontSize 13
}
skinparam rectangle {
  BorderColor #222222
  BackgroundColor white
}

actor "Super admin" as SuperAdmin
actor "Quản lý tòa nhà" as BuildingManager

rectangle "Hệ thống StayHub Admin Web" {
  usecase "Quản lí bảo trì" as Main
  usecase "Xem danh sách yêu cầu bảo trì" as ListMaintenance
  usecase "Xem chi tiết yêu cầu" as ViewMaintenance
  usecase "Cập nhật trạng thái bảo trì" as UpdateStatus
  usecase "Tải ảnh minh chứng xử lý" as UploadProof
  usecase "Xem đánh giá bảo trì" as ViewFeedback
  usecase "Tìm kiếm/lọc yêu cầu" as FilterMaintenance
}

ListMaintenance ..> Main : <<extend>>
ViewMaintenance ..> Main : <<extend>>
UpdateStatus ..> Main : <<extend>>
UploadProof ..> Main : <<extend>>
ViewFeedback ..> Main : <<extend>>
FilterMaintenance ..> Main : <<extend>>
SuperAdmin -- Main
BuildingManager -- Main
@enduml
