@startuml UC_21_NhatKyAdmin
left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam shadowing false
skinparam usecase {
  BackgroundColor white
  BorderColor #222222
  ArrowColor #222222
  FontSize 13
}
skinparam rectangle {
  BorderColor #222222
  BackgroundColor white
}

actor "Super admin" as SuperAdmin

rectangle "Hệ thống StayHub Admin Web" {
  usecase "Xem nhật ký admin" as Main
  usecase "Xem danh sách nhật ký" as ListLogs
  usecase "Xem chi tiết nhật ký" as ViewLog
  usecase "Tìm kiếm/lọc nhật ký" as FilterLog
  usecase "Theo dõi hành động admin" as TrackAction
}

ListLogs ..> Main : <<extend>>
ViewLog ..> Main : <<extend>>
FilterLog ..> Main : <<extend>>
TrackAction ..> Main : <<extend>>
SuperAdmin -- Main
@enduml
